import { NextAuthWrapper } from '@/lib/index'
import { Providers } from '@/lib/index'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthWrapper>
          <Providers>
            {children}
          </Providers>
        </NextAuthWrapper>
      </body>
    </html>
  )
}
